
project_id = "dzzptovqfqausipsgabw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://dzzptovqfqausipsgabw.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.create_square_checkout]
verify_jwt = false

[functions.square_webhook]
verify_jwt = false

[functions.create_checkout_session]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.generate-design-image]
verify_jwt = false
