
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzzptovqfqausipsgabw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6enB0b3ZxZnFhdXNpcHNnYWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MDM1MjksImV4cCI6MjA2MTk3OTUyOX0.7jSsV-y-32C7f23rw6smPPzuQs6HsQeKpySP4ae_C5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Add storageUrl getter for convenience
Object.defineProperty(supabase, 'storageUrl', {
  get() {
    return `${SUPABASE_URL}/storage/v1`;
  }
});

// Add avatarUrl helper function
export const getAvatarUrl = (path: string | null) => {
  if (!path) return null;
  return `${SUPABASE_URL}/storage/v1/object/public/avatars/${path}`;
};

// Since we can't directly modify the types.ts file automatically, we need to inform
// the user about the need to regenerate types or create a custom types workaround
